### ISSUE TITLE
Verifying `vest` crate and `vest-examples` fail

### ISSUE THREAD

**Issue by BlastWind** [secure-foundations/vest#15]
Cool work guys! I want to read your repo as a good case study for what `Verus` can do.

But when I follow the development docs, `make`ing the `vest` folder and `vest-examples` folder gave plenty errors.

When making `vest`, I'm getting `error[E0277]: the size for values of type `Self` cannot be known at compilation time` in `src/buf_traits.rs`. 

When making `vest-examples`, I'm getting lots of `not found in this scope` errors for what seems to be primitives like `Bytes`, Tag`, etc.

```
Verus
  Version: 0.2024.12.18.a5a57fe
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.79.0-aarch64-apple-darwin

rustc 1.83.0 (90b35a623 2024-11-26)
```

**Comment by pratapsingh1729** [comment]
Thanks for your interest in Verus and Vest!

Unfortunately, due to a [Verus issue](https://github.com/verus-lang/verus/issues/1339), Vest doesn't work with Verus versions that use the Rust 1.79.0 toolchain. Vest is known to work with older versions that use Rust 1.76.0; for instance, I'm using the following Verus version and am able to verify and compile `vest` and `vest-examples`:
```
Verus
  Version: 0.2024.10.11.dba7a12
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.76.0-aarch64-apple-darwin
```
You might also need to set your `rustup` toolchain to use 1.76.0 when building Verus. We're hoping to get the issue fixed and then migrate to the most recent Verus version.

Note that the `vest-examples` crate depends on `vest`, so it requires that `vest` has already been compiled and verified. In the [Makefile for `vest-examples`](https://github.com/secure-foundations/vest/blob/main/vest-examples/Makefile), the arguments `--import vest=../vest/vest.verusdata --extern vest=../vest/libvest.rlib` are telling Verus to include the compiled Verus and Rust data for `vest`. In future, Verus will support `cargo` integration, so these kinds of dependency management hacks will not be necessary.

Please do let us know if you run into any more issues!

**Comment by y1ca1** [comment]
Thanks for your interest! Fwiw, `Vest` doesn't use any fancy features of `Verus` like its ability to reason about `unsafe` code, interior mutability, concurrency, etc. But it is a very good case study for `Verus`'s basic functionalities and its current support in traits. You may find useful [Supported Rust Features in Verus](https://verus-lang.github.io/verus/guide/features.html#supported-rust-features).

**Comment by BlastWind** [comment]
Thanks for the quick response Pratap. And thanks for the pointers, Yi. This works for me, hopefully the upstream Verus issues get fixed soon :)

**Comment by BlastWind** [comment]
Hey folks, though downgrading to exactly

```
Verus
  Version: 0.2024.10.11.dba7a12
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.76.0-aarch64-apple-darwin
```

got `make` to work in `vest/vest` and `vest/vest-examples`, commands in `vest/vest-dsl` don't work. If I run `cargo run path/to/your/file.vest` or `cargo install --path .` in `vest/vest-dsl`, I get 

```rust
error[E0716]: temporary value dropped while borrowed
   --> src/codegen.rs:645:32
    |
644 |             let type_alias_name = match mode {
    |                 --------------- borrow later stored here
645 |                 Mode::Spec => &format!("Spec{}", name),
    |                                ^^^^^^^^^^^^^^^^^^^^^^-
    |                                |                     |
    |                                |                     temporary value is freed at the end of this statement
    |                                creates a temporary value which is freed while still in use
    |
    = note: consider using a `let` binding to create a longer lived value
    = not

...

error: could not compile `vest-dsl` (bin "vest-dsl") due to 15 previous errors

...
```

Are there any workarounds for this?

**Comment by BlastWind** [comment]
Also, while I have your attention, I'll be grateful if you can answer any of the following rapid fire questions I have regarding `vest`: 

1. Where did the terms “prefix security” and “productivity” originate from? They are intuitive, but I didn’t find mentions of them in literature.
2. Which property of which secure combinator was the hardest to implement?
3. What’s missing of `vest` from a first release?
4. Do the following traditional parser properties have correspondents in PEG parsers? I feel that both soundness and completeness are CFG-specific. But perhaps, the roundtrip properties imply unambiguity? These traditional properties can be found in Barthwal et al.'s [Verified, Executable Parsing](https://users.cecs.anu.edu.au/~aditi/esop09_submission_16.pdf), 
    1. Soundness: If the parser produces an output, that output is correct. I.e., if a parse tree $T$ is constructed from input string $w$, then $T$ is valid in the grammar. And, reading the leaves of $T$ from left-to-right gives you $w$,
    2. Completeness: The parser produces an output for every valid input,
    3. Unambiguity: Each input string has exactly one valid parse tree.
6. Is it possible to construct a non-terminating `vest` parser that is built with `SecureSpecCombinator`? If not, which property subsumes and guarantees totality?

**Comment by y1ca1** [comment]
> Hey folks, though downgrading to exactly
> 
> ```
> Verus
>   Version: 0.2024.10.11.dba7a12
>   Profile: release
>   Platform: macos_aarch64
>   Toolchain: 1.76.0-aarch64-apple-darwin
> ```
> 
> got `make` to work in `vest/vest` and `vest/vest-examples`, commands in `vest/vest-dsl` don't work. If I run `cargo run path/to/your/file.vest` or `cargo install --path .` in `vest/vest-dsl`, I get
> 
> error[E0716]: temporary value dropped while borrowed
>    --> src/codegen.rs:645:32
>     |
> 644 |             let type_alias_name = match mode {
>     |                 --------------- borrow later stored here
> 645 |                 Mode::Spec => &format!("Spec{}", name),
>     |                                ^^^^^^^^^^^^^^^^^^^^^^-
>     |                                |                     |
>     |                                |                     temporary value is freed at the end of this statement
>     |                                creates a temporary value which is freed while still in use
>     |
>     = note: consider using a `let` binding to create a longer lived value
>     = not
> 
> ...
> 
> error: could not compile `vest-dsl` (bin "vest-dsl") due to 15 previous errors
> 
> ...
> Are there any workarounds for this?

Hi!

So first of all, a good news is that the verified `vest` crate should work with the latest Verus commit/release now!

For the DSL, I'd recommend using the latest stable Rust (1.84) and try `cargo run` again.

**Comment by y1ca1** [comment]
> 1. Where did the terms “prefix security” and “productivity” originate from? They are intuitive, but I didn’t find mentions of them in literature.

Those are excellent questions! So we just submitted a paper for Vest and for anonymity issues Idk if we can publish/put it on arXiv yet, but simply put, “prefix security” means a parser won't change its behavior in any way when the input buffer is _extended_; "productivity" means a parser/serializer would consume/produce _a least one_ byte when they succeed. Technically, "Prefix security" is discussed before in literature like [EverParse](https://www.usenix.org/conference/usenixsecurity19/presentation/delignat-lavaud) (Section 5, Definition 2). While "productivity" hasn't been discussed before formally in the context of parsing security, it's similar and related to the _non-emptiness_ requirements on certain regexes in the theory of derivatives of regular expressions.

> 2. Which property of which secure combinator was the hardest to implement?

IIRC, the roundtrip theorems for `Depend`, `OrdChoice`, `RepeatN`, and `Repeat` are quite subtle to prove (these are basically the (dependent) sequencing, choice, and repetitive combinators), and the `exec-spec` equivalence for `RepeatN`, and `Repeat` are the hardest to verify.

> 3. What’s missing of `vest` from a first release?

Good question! So we're currently working on and need to work on mainly three things before the first Vest release:
1. Our serialization interface is quite unergonomic and inefficient currently, mainly due to the fact that `serialize` is taking an _owned_ value and the value needs to be _dropped_ during serialization. We're actively working on solutions on this issue at the [ref-serialize](https://github.com/secure-foundations/vest/tree/ref-serialize) branch, and so far it looks promising (modulo some Verus issues that's not inherently hard to address).
2. Our benchmark results are currently scattered all over the places (welcome to the life of PhD students), and we need to consolidate them quite a bit to back our (performance) claims.
3. Currently our DSL is only developed for "good programs", which means it can (and will) give _horrible_ error messages for "bad programs". To have the DSL truly usable, we need _at least_ a big refactor of the type checking pass of the DSL compiler (the `vest-dsl` crate).

Some other considerations would be better user experience for `vest` library users, better documentation, (potentially) tutorials, crates.io registration, etc.

> 5. Do the following traditional parser properties have correspondents in PEG parsers? I feel that both soundness and completeness are CFG-specific. But perhaps, the roundtrip properties imply unambiguity? These traditional properties can be found in Barthwal et al.'s [Verified, Executable Parsing](https://users.cecs.anu.edu.au/~aditi/esop09_submission_16.pdf),>    
>    1. Soundness: If the parser produces an output, that output is correct. I.e., if a parse tree 
>         T
>        is constructed from input string 
>         w
>       , then 
>         T
>        is valid in the grammar. And, reading the leaves of 
>         T
>        from left-to-right gives you 
>         w
>       ,
>    2. Completeness: The parser produces an output for every valid input,
>    3. Unambiguity: Each input string has exactly one valid parse tree.

Yes. So our parser combinators (resembling PEG parsers) are proved for bi-directionality (roundtrips in both directions), from which we have [soundness](https://github.com/secure-foundations/vest/blob/74a354ff8a10bbf0ea0676d30b44103b17837c54/vest/src/properties.rs#L44) and [completeness](https://github.com/secure-foundations/vest/blob/74a354ff8a10bbf0ea0676d30b44103b17837c54/vest/src/properties.rs#L52) automatically. We also have derived [non-ambiguity](https://github.com/secure-foundations/vest/blob/74a354ff8a10bbf0ea0676d30b44103b17837c54/vest/src/properties.rs#L72) and [non-malleability](https://github.com/secure-foundations/vest/blob/74a354ff8a10bbf0ea0676d30b44103b17837c54/vest/src/properties.rs#L104), depending on from what perspective you view them. 

> 5. Is it possible to construct a non-terminating `vest` parser that is built with `SecureSpecCombinator`? If not, which property subsumes and guarantees totality?

No. So Veurs `spec` functions are pure, total, functional programs, where one has to prove totality for every `spec` function definitions (through termination proofs), and we prove the behavioral equivalence for every `exec` combinator against their `spec`, which in turn guarantees totality.

**Comment by BlastWind** [comment]
@y1ca1 Beautiful, thank you so much! This answers my questions perfectly.

Good luck on the PhD grind, it's tough but you are building very useful utilities with it. I look forward to the paper — if you plan to have a section on "usability" or "real developer feedback", I'll be happy to contribute. 

Oh, and happy Lunar New Years!
